version: '2'
services:
    producer:
        build: .
        ports: 
            - 8888:8888
        depends_on:
            - kafka
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - KAFKA_URL=kafka
            - KAFKA_PORT=9092
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"