version: '2'
services:
    producer:
        build:
            context: .
            dockerfile: Dockerfile_producer
        ports: 
            - 8888:8888
        depends_on:
            - kafka
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - KAFKA_URL=kafka:9092
            - KAFKA_SYNC_TOPIC=sync-topic
            - KAFKA_ASYNC_TOPIC=async-topic
            - KAFKA_PARTITION=0
    sync_consumer:
        build:
            context: .
            dockerfile: Dockerfile_consumer
        depends_on:
            - kafka
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - KAFKA_URL=kafka:9092
            - KAFKA_TOPIC_TO_CONSUMER=sync-topic
            - KAFKA_PARTITION=0
    async_consumer:
        build:
            context: .
            dockerfile: Dockerfile_consumer
        depends_on:
            - kafka
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - KAFKA_URL=kafka:9092
            - KAFKA_TOPIC_TO_CONSUMER=async-topic
            - KAFKA_PARTITION=0
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"